# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.folders_selection_layout = QtWidgets.QHBoxLayout()
        self.folders_selection_layout.setSpacing(4)
        self.folders_selection_layout.setObjectName("folders_selection_layout")
        self.origin_folder_layout = QtWidgets.QHBoxLayout()
        self.origin_folder_layout.setSpacing(1)
        self.origin_folder_layout.setObjectName("origin_folder_layout")
        self.origin_folder_label = QtWidgets.QLabel(self.centralwidget)
        self.origin_folder_label.setObjectName("origin_folder_label")
        self.origin_folder_layout.addWidget(self.origin_folder_label)
        self.origin_folder_button = QtWidgets.QPushButton(self.centralwidget)
        self.origin_folder_button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.origin_folder_button.setObjectName("origin_folder_button")
        self.origin_folder_layout.addWidget(self.origin_folder_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.origin_folder_layout.addItem(spacerItem)
        self.folders_selection_layout.addLayout(self.origin_folder_layout)
        self.sync_folders_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.sync_folders_checkbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sync_folders_checkbox.setToolTipDuration(-1)
        self.sync_folders_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sync_folders_checkbox.setChecked(True)
        self.sync_folders_checkbox.setObjectName("sync_folders_checkbox")
        self.folders_selection_layout.addWidget(self.sync_folders_checkbox)
        self.destination_folder_group = QtWidgets.QWidget(self.centralwidget)
        self.destination_folder_group.setEnabled(False)
        self.destination_folder_group.setObjectName("destination_folder_group")
        self.destination_folder_layout = QtWidgets.QHBoxLayout(self.destination_folder_group)
        self.destination_folder_layout.setSpacing(1)
        self.destination_folder_layout.setObjectName("destination_folder_layout")
        self.destination_folder_label = QtWidgets.QLabel(self.destination_folder_group)
        self.destination_folder_label.setObjectName("destination_folder_label")
        self.destination_folder_layout.addWidget(self.destination_folder_label)
        self.destination_folder_button = QtWidgets.QPushButton(self.destination_folder_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destination_folder_button.sizePolicy().hasHeightForWidth())
        self.destination_folder_button.setSizePolicy(sizePolicy)
        self.destination_folder_button.setMaximumSize(QtCore.QSize(20, 16777215))
        self.destination_folder_button.setObjectName("destination_folder_button")
        self.destination_folder_layout.addWidget(self.destination_folder_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.destination_folder_layout.addItem(spacerItem1)
        self.folders_selection_layout.addWidget(self.destination_folder_group)
        self.verticalLayout.addLayout(self.folders_selection_layout)
        self.image_interaction_layout = QtWidgets.QHBoxLayout()
        self.image_interaction_layout.setObjectName("image_interaction_layout")
        self.image_display_scrollarea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_display_scrollarea.sizePolicy().hasHeightForWidth())
        self.image_display_scrollarea.setSizePolicy(sizePolicy)
        self.image_display_scrollarea.setWidgetResizable(True)
        self.image_display_scrollarea.setObjectName("image_display_scrollarea")
        self.image_scrollarea_widget = QtWidgets.QWidget()
        self.image_scrollarea_widget.setGeometry(QtCore.QRect(0, 0, 585, 556))
        self.image_scrollarea_widget.setObjectName("image_scrollarea_widget")
        self.image_scrollarea_layout = QtWidgets.QVBoxLayout(self.image_scrollarea_widget)
        self.image_scrollarea_layout.setObjectName("image_scrollarea_layout")
        self.image_display_label = QtWidgets.QLabel(self.image_scrollarea_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_display_label.sizePolicy().hasHeightForWidth())
        self.image_display_label.setSizePolicy(sizePolicy)
        self.image_display_label.setObjectName("image_display_label")
        self.image_scrollarea_layout.addWidget(self.image_display_label)
        self.image_display_scrollarea.setWidget(self.image_scrollarea_widget)
        self.image_interaction_layout.addWidget(self.image_display_scrollarea)
        self.file_interaction_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_interaction_frame.sizePolicy().hasHeightForWidth())
        self.file_interaction_frame.setSizePolicy(sizePolicy)
        self.file_interaction_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.file_interaction_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.file_interaction_frame.setObjectName("file_interaction_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.file_interaction_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_label = QtWidgets.QLabel(self.file_interaction_frame)
        self.header_label.setObjectName("header_label")
        self.verticalLayout_2.addWidget(self.header_label)
        self.files_listview = QtWidgets.QListView(self.file_interaction_frame)
        self.files_listview.setObjectName("files_listview")
        self.verticalLayout_2.addWidget(self.files_listview)
        self.filename_save_layout = QtWidgets.QVBoxLayout()
        self.filename_save_layout.setObjectName("filename_save_layout")
        self.file_name_layout = QtWidgets.QHBoxLayout()
        self.file_name_layout.setSpacing(2)
        self.file_name_layout.setObjectName("file_name_layout")
        self.filename_lineedit = QtWidgets.QLineEdit(self.file_interaction_frame)
        self.filename_lineedit.setObjectName("filename_lineedit")
        self.file_name_layout.addWidget(self.filename_lineedit)
        self.file_format_combobox = QtWidgets.QComboBox(self.file_interaction_frame)
        self.file_format_combobox.setObjectName("file_format_combobox")
        self.file_format_combobox.addItem("")
        self.file_format_combobox.addItem("")
        self.file_name_layout.addWidget(self.file_format_combobox)
        self.filename_save_layout.addLayout(self.file_name_layout)
        self.file_save_button_layout = QtWidgets.QHBoxLayout()
        self.file_save_button_layout.setObjectName("file_save_button_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.file_save_button_layout.addItem(spacerItem2)
        self.save_button = QtWidgets.QPushButton(self.file_interaction_frame)
        self.save_button.setObjectName("save_button")
        self.file_save_button_layout.addWidget(self.save_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.file_save_button_layout.addItem(spacerItem3)
        self.filename_save_layout.addLayout(self.file_save_button_layout)
        self.verticalLayout_2.addLayout(self.filename_save_layout)
        self.image_interaction_layout.addWidget(self.file_interaction_frame)
        self.verticalLayout.addLayout(self.image_interaction_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.origin_folder_label.setText(_translate("MainWindow", "Select origin folder"))
        self.origin_folder_button.setToolTip(_translate("MainWindow", "Browse to folder"))
        self.origin_folder_button.setText(_translate("MainWindow", "..."))
        self.sync_folders_checkbox.setToolTip(_translate("MainWindow", "Save new files to same folder as origin"))
        self.sync_folders_checkbox.setText(_translate("MainWindow", "Sync"))
        self.destination_folder_label.setText(_translate("MainWindow", "Select destination folder"))
        self.destination_folder_button.setToolTip(_translate("MainWindow", "Browse to folder"))
        self.destination_folder_button.setText(_translate("MainWindow", "..."))
        self.image_display_label.setText(_translate("MainWindow", "Image Display"))
        self.header_label.setText(_translate("MainWindow", "Files"))
        self.filename_lineedit.setPlaceholderText(_translate("MainWindow", "New filename"))
        self.file_format_combobox.setToolTip(_translate("MainWindow", "Format to save the image"))
        self.file_format_combobox.setCurrentText(_translate("MainWindow", ".PNG"))
        self.file_format_combobox.setItemText(0, _translate("MainWindow", ".PNG"))
        self.file_format_combobox.setItemText(1, _translate("MainWindow", ".JPG"))
        self.save_button.setToolTip(_translate("MainWindow", "Save image with entered filename"))
        self.save_button.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

